FROM maven:3.9.4-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml ./
COPY src ./src
RUN mvn -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /build/target/recipe-backend-1.0.0-jar-with-dependencies.jar /app/app.jar
EXPOSE 7001
CMD ["java","-jar","/app/app.jar"]
